runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: RetirementPlanner/website/index.html
  upload: RetirementPlanner/website/index.html

- url: /
  static_dir: RetirementPlanner/website